/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.srdjanv.hotswapgradle;

import static org.junit.jupiter.api.Assertions.*;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

class HotSwapGradlePluginTest {
    @Test
    void pluginRegistersATask() {
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("io.github.srdjan-v.hotswap-gradle");

        assertDoesNotThrow(() -> project.getGradle()
                .getSharedServices()
                .getRegistrations()
                .getByName(HotswapGradleService.class.getName()));
    }
}
